services:
  #MySQL(データベースのコンテナ情報)
  lesson02_Mysql:
    build: ./mysql/
    container_name: "lesson_Mysql"
    volumes:
      # - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでOK
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    image: mysqlapp
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass1234
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=mysqlpass1234

#=====追加部分=====
      - MYSQL_DATABASE=mydatabase    # データベースを自動作成
#=====追加部分=====

      - TZ='Asia/Tokyo'
    ports:
    - 3306:3306
    # IPアドレスの固定
    networks:
      lesson02_network:
        ipv4_address: 192.168.2.8

#=====追加部分=====
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
#=====追加部分=====

  #Python(Djangoのコンテナ情報)
  lesson02_django:
    build: ./django/
    container_name: 'lesson_django'
    restart: always
    tty: true #正常終了させないための仮プロセス
    ports:
      - "8000:8000" #Django用
    volumes:
      - ./django/dir:/workdir/dir
    networks:
        - lesson02_network
    depends_on:

#=====変更部分=====
      lesson02_Mysql:
        condition: service_healthy    # MySQLが健全な状態になるまで待機
#=====変更部分=====

#Docker内で使用するネットワークの設定
networks: 
  lesson02_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.2.0/24
        gateway: 192.168.2.1
    